name: Uruchom Selenium Scraper

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest # Ten system ma już Chrome zainstalowanego!

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Scraper
        # To uruchomi klasę zdefiniowaną w build.gradle w sekcji application { mainClass = ... }
        run: ./gradlew run
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}